### ISSUE TITLE
Few questions and overview

### ISSUE THREAD

**Issue by Tamerkadan** [keedio/nagios-hadoop#8]
Hi,
First thanks for the contribution ,
Second, can you give an overview of nagios/hadoop check? 
What output it will give us?

Another major issue, can it be used at storm/stormnimbus servers?
@jdgonzalez-keedio  @jucaf 
Thanks a lot

**Comment by jucaf** [comment]
There are 3 check_hadoop_ files,
check_hadoop_hdfs checks hdfs status (%used storage, total amount of blocks in use, datanodes balancing, corrupted blocks, missing blocks, under replicated blocks, check if one and only one NN is active and one in standby)
check_hadoop_httpfs check httpfs sanity (writable, file/directory owner group permission)
and check_hadoop_journalnode check journalnodes sanity (time taken to process requests, in sync journalnodes and quorum state)

To check storm you can use https://github.com/keedio/nagios-hadoop/blob/master/check_storm.py and https://github.com/keedio/nagios-hadoop/blob/master/stormStatus.py

**Comment by Tamerkadan** [comment]
Thanks for the detailed answer.

What is the storm checks do ?

**Comment by jucaf** [comment]
it check bolts load and latency.

**Comment by Tamerkadan** [comment]
Thanks !
